version: '3'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  mysqldb:
    image: mysql/mysql-server
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1qazzaq1
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

networks:
  backend:
    driver: bridge
