name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@ec2-54-251-192-199.ap-southeast-1.compute.amazonaws.com'
          privateKey: ${{ secrets.EC2_SSH_KEY }}
          command: |
            cd ~/projects/hw-metasource-backend
            git checkout deploy.sh
            chmod +x deploy.sh
            sudo ./deploy.sh
